// Code generated by go generate; DO NOT EDIT.
// This file was generated by scripts/models/gen_nullable_types.go
package nullable

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/go-openapi/strfmt"
)

// Bool represents a bool that may be null or not
// present in json at all.
type Bool struct {
	Present bool // Present is true if key is present in json
	Valid   bool // Valid is true if value is not null and valid bool
	Value   bool
}

// Returns nil if not present or valid. Otherwise it will
// return a pointer to the value.
func (b *Bool) Ptr() *bool {
	if b.Present && b.Valid {
		return &b.Value
	}

	return nil
}

// UnmarshalJSON implements json.Marshaler interface.
func (b *Bool) UnmarshalJSON(data []byte) error {
	b.Present = true

	if bytes.Equal(data, null) {
		return nil
	}

	if err := json.Unmarshal(data, &b.Value); err != nil {
		return err
	}

	b.Valid = true
	return nil
}

// Validate implements runtime.Validateable interface from github.com/go-openapi/runtime
func (b *Bool) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate implements runtime.ContextValidatable from github.com/go-openapi/runtime
func (b *Bool) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// BoolSlice represents a []bool that may be null or not
// present in json at all.
type BoolSlice struct {
	Present bool // Present is true if key is present in json
	Valid   bool // Valid is true if value is not null
	Value   []bool
}

// UnmarshalJSON implements json.Marshaler interface.
func (b *BoolSlice) UnmarshalJSON(data []byte) error {
	b.Present = true

	if bytes.Equal(data, null) {
		return nil
	}

	if err := json.Unmarshal(data, &b.Value); err != nil {
		return err
	}

	b.Valid = true
	return nil
}

// Returns nil if not present or valid. Otherwise it will
// return a pointer to the value.
func (b *BoolSlice) Ptr() *[]bool {
	if b.Present && b.Valid {
		return &b.Value
	}

	return nil
}

// Validate implements runtime.Validateable interface from github.com/go-openapi/runtime
func (b *BoolSlice) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate implements runtime.ContextValidatable from github.com/go-openapi/runtime
func (b *BoolSlice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
