// Code generated by go generate; DO NOT EDIT.
// This file was generated by scripts/models/gen_nullable_types.go
package nullable

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Compile time validation that our types implement the expected interfaces
var (
	_ runtime.Validatable        = &String{}
	_ runtime.ContextValidatable = &String{}
	_ runtime.Validatable        = &StringSlice{}
	_ runtime.ContextValidatable = &StringSlice{}
)

// String represents a string that may be null or not
// present in json at all.
type String struct {
	Present bool // Present is true if key is present in json
	Valid   bool // Valid is true if value is not null and valid string
	Value   string
}

// Returns nil if not present or valid. Otherwise it will
// return a pointer to the value.
func (s *String) Ptr() *string {
	if s.Present && s.Valid {
		return &s.Value
	}

	return nil
}

// UnmarshalJSON implements json.Marshaler interface.
func (s *String) UnmarshalJSON(data []byte) error {
	s.Present = true

	if bytes.Equal(data, null) {
		return nil
	}

	if err := json.Unmarshal(data, &s.Value); err != nil {
		return err
	}

	s.Valid = true
	return nil
}

// Validate implements runtime.Validateable interface from github.com/go-openapi/runtime
func (s *String) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate implements runtime.ContextValidatable from github.com/go-openapi/runtime
func (s *String) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// StringSlice represents a []string that may be null or not
// present in json at all.
type StringSlice struct {
	Present bool // Present is true if key is present in json
	Valid   bool // Valid is true if value is not null
	Value   []string
}

// UnmarshalJSON implements json.Unmarshaler interface.
func (s *StringSlice) UnmarshalJSON(data []byte) error {
	s.Present = true

	if bytes.Equal(data, null) {
		return nil
	}

	if err := json.Unmarshal(data, &s.Value); err != nil {
		return err
	}

	s.Valid = true
	return nil
}

// Returns nil if not present or valid. Otherwise it will
// return a pointer to the value.
func (s *StringSlice) Ptr() *[]string {
	if s.Present && s.Valid {
		return &s.Value
	}

	return nil
}

// Validate implements runtime.Validateable interface from github.com/go-openapi/runtime
func (s *StringSlice) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate implements runtime.ContextValidatable from github.com/go-openapi/runtime
func (s *StringSlice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
